### ISSUE TITLE
Is jdkIncludePath suppose to do something?

### ISSUE THREAD

**Issue by kwhat** [mojohaus/maven-native#35]
I am seeing errors like `fatal error: jni.h: No such file or directory` when trying to use jdkIncludePath in a compile goal.  What does this configuration do, and more importantly why doesn't it add an include (-I) to the C src compilation? If this is for something else and I still need to add a `<source><directory>${java.home}/include</directory></source>` why does it even exist?

**Comment by dantran** [comment]
@kwhat may want to take a look at this   https://github.com/mojohaus/maven-native/issues/17

**Comment by kwhat** [comment]
Yah, I was reading that earlier... maintaining backward compatibility is really a lost cause <1.8 || <11.  It seems that jdkIncludePath really doesn't do anything meaningful unless you specify `<javahOS/>`, even when only compiling native src without javah.

**Comment by kwhat** [comment]
I finally got it working, took a bit of monkeying but it works well, thanks!

**Comment by gbaudic** [comment]
I ran across a similar issue, and I am curious to know which workaround you ended up using. 

It turns out that for Java 11 at least (but this likely applies to later versions as well), the default value for `jdkIncludePath` of `${java.home}/../include` that is assumed by this plugin is no longer correct, hence the error. You have to explicitly declare it in your pom as `${java.home}/include`.
